import type { Metadata } from "next";
import {Barlow, Poppins} from 'next/font/google'
import './globals.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateViewport() {  
  return {  
      width: 'device-width',  
      initialScale: 1,  
      maximumScale: 1,  
      userScaled: 'no', // Para impedir o zoom  
  };  
}  

const barlow = Barlow({
  weight: ['500', '600'],
  subsets: ['latin'],
  variable: '--font-barlow'
})

const poppins = Poppins({
  weight: ['100', '200','300', '400','500', '600'],
  subsets: ['latin'],
  variable: '--font-poppins'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${barlow.variable} ${poppins.variable}`}>
      <body>{children}</body>
    </html>
  );
}
